enthalpy:  
  numerics: 
    Nz: 10
    vert_spacing: 4.0
  solver:
    allow_basal_refreezing: True
    correct_w_for_melt: True
    override_basal_at_pmp: False
  thermal:
    T_min: 243.15
    T_pmp_ref: 273.15
    T_ref: 223.15
    c_ice: 2009.0
    L_ice: 3.34e+5
    k_ice: 2.1
    K_ratio: 1e-1
    basal_heat_flux_ref: 0.065
    beta: 7.9e-8
  surface:
    T_offset: 0.0
  arrhenius:
    A_cold: 3.985e-13
    A_warm: 1.916e+3
    Q_cold: 60000.0
    Q_warm: 139000.0
    T_threshold: 263.15
    omega_coef: 181.25
    omega_max: 0.01
    R: 8.314
  till:
    friction:
      phi: 30.0
      phi_min: 15.0
      phi_max: 45.0
      bed_min: null
      bed_max: null
      tauc_min: 1.0e+5
      tauc_max: 1.0e+10
      tauc_ice_free: 1.0e+6
      u_ref: 100.0
    hydro:
      h_water_till_max: 2.0
      N_ref: 1000.0
      e_ref: 0.69
      C_c: 0.12
      delta: 0.02
      drainage_rate: 0.001
  drainage:
    water_density: 1000.0
    drain_ice_column: True
    omega_target: 0.00
    omega_threshold_1: 0.01
    omega_threshold_2: 0.02
    omega_threshold_3: 0.03    